parameters:
#    user.example.class: Tinkernote\UserBundle\Example

services:
    tinkernote_user.registration.form.type:
        class: Tinkernote\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: tinkernote_user_registration }

    tinkernote_user.profile.form.type:
        class: Tinkernote\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: form.type, alias: tinkernote_user_profile }
