<?php

namespace Tinkernote\SiteBundle\Entity\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnementActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementActivityRepository extends EntityRepository
{
    public function getAbonnementActivity($user)
    {
        $qb = $this->createQueryBuilder('a')
             ->select('a','b','c')
            ->leftJoin('a.follower', 'b')
            ->leftJoin('a.followed', 'c')
            ->where('b.id = :follower')
            ->orWhere('c.id = :followed')
            ->orderBy('a.date', 'DESC')
            ->setParameters(array('follower' => $user, 'followed' => $user))
            ->getQuery();

        $response = $qb->execute();

        return $response;
    }
}
