<?php

namespace Tinkernote\SiteBundle\Entity\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceActivityRepository extends EntityRepository
{

}
