site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

bloc_homepage:
    path:     /board
    defaults: { _controller: SiteBundle:Board:index }

comment_add:
    path:      /AddComment
    defaults:  { _controller: SiteBundle:Comment:addComment }

annonce_homepage:
    path:     /annonce
    defaults: { _controller: SiteBundle:Annonce:index }

annonce_show:
    path:     /show-annonce/{id}
    defaults: { _controller: SiteBundle:Annonce:show }
    requirements:
        id: \d+

annonce_usershow:
    path:     /show-annonces/user/{id}
    defaults: { _controller: SiteBundle:Annonce:UserAnnonce }
    requirements:
        id: \d+

annonce_add:
    path:     /add-annonce
    defaults: { _controller: SiteBundle:Annonce:add }

site_soon:
    path:     /soon
    defaults: { _controller: SiteBundle:Site:soon }

site_rempli:
    path:     /rempli
    defaults: { _controller: SiteBundle:Site:rempli }

site_rempli_category:
    path:    /rempli-category
    defaults: { _controller: SiteBundle:Site:rempliCategory }

site_rempli_postal:
    path:     /rempli-postal/{cp}
    defaults: { _controller: SiteBundle:Site:rempliPostal }
    requirements:
        cp: \d+

recherche_annonce:
    path:     /rechercher
    defaults: { _controller: SiteBundle:Recherche:rechercheTraitement }

recherche_annonce_principal:
    path:     /rechercher-annonce
    defaults: { _controller: SiteBundle:Recherche:recherchePrincipal }

recherche_annonce_header:
    path:     /rechercher-header
    defaults: { _controller: SiteBundle:Recherche:headbarsearch }

categorie_annonce:
    path:    /categorie/{categorie}
    defaults: { _controller: SiteBundle:Annonce:categorie }

ville_annonce:
    path:    /ville/{ville}
    defaults: { _controller: SiteBundle:Annonce:ville }

region_annonce:
    path:    /region/{region}
    defaults: { _controller: SiteBundle:Annonce:region }

upload_file_route:
    path: /upload-file
    defaults: { _controller: SiteBundle:Picture:plupload }

board_edit_annonce:
    path: /board/edit/{id}
    defaults: { _controller: SiteBundle:Board:editAnnonce }
    requirements:
        id: \d+

board_remove_annonce:
    path: /board/remove/{id}
    defaults: { _controller: SiteBundle:Board:deleteAnnonce }
    requirements:
        id: \d+

board_add_whatsup:
    path: /board/whatsup
    defaults: { _controller: SiteBundle:Board:ajaxWhatsUp }

board_add_followed:
    path: /board/add-followed/{followed}
    defaults: { _controller: SiteBundle:Abonnement:index }
    requirements:
        followed: \d+

board_remove_followed:
    path: /board/remove-followed/{followed}
    defaults: { _controller: SiteBundle:Abonnement:desabonnement }
    requirements:
        followed: \d+

board_remove_region_followed:
    path: /board/remove-region-followed/{followed}
    defaults: { _controller: SiteBundle:Abonnement:desabonnementRegion }
    requirements:
        followed: \d+

board_add_region_followed:
    path: /board/add-region-followed/{followed}
    defaults: { _controller: SiteBundle:Abonnement:abonnementRegion }
    requirements:
        followed: \d+

board_my_abonnement:
    path: /board/abonnement
    defaults: { _controller: SiteBundle:Abonnement:myAbonnement }