site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Site:index }

bloc_homepage:
    path:     /board
    defaults: { _controller: SiteBundle:Board:index }

comment_add:
    path:      /AddComment
    defaults:  { _controller: SiteBundle:Comment:addComment }

annonce_homepage:
    path:     /annonce
    defaults: { _controller: SiteBundle:Annonce:index }

annonce_show:
    path:     /show-annonce/{id}
    defaults: { _controller: SiteBundle:Annonce:show }

annonce_add:
    path:     /add-annonce
    defaults: { _controller: SiteBundle:Annonce:add }

site_soon:
    path:     /soon
    defaults: { _controller: SiteBundle:Site:soon }

site_rempli:
    path:     /rempli
    defaults: { _controller: SiteBundle:Site:rempli }

site_rempli_category:
    path:    /rempli-category
    defaults: { _controller: SiteBundle:Site:rempliCategory }

site_rempli_postal:
    path:     /rempli-postal/{cp}
    defaults: { _controller: SiteBundle:Site:rempliPostal }

recherche_annonce:
    path:     /rechercher
    defaults: { _controller: SiteBundle:Recherche:rechercheTraitement }

recherche_annonce_principal:
    path:     /rechercher-annonce
    defaults: { _controller: SiteBundle:Recherche:recherchePrincipal }

categorie_annonce:
    path:    /categorie/{categorie}
    defaults: { _controller: SiteBundle:Annonce:categorie }

ville_annonce:
    path:    /ville/{ville}
    defaults: { _controller: SiteBundle:Annonce:ville }

region_annonce:
    path:    /region/{region}
    defaults: { _controller: SiteBundle:Annonce:region }

upload_file_route:
    path: /upload-file
    defaults: { _controller: SiteBundle:Picture:plupload }