parameters:
#    site.example.class: Tinkernote\SiteBundle\Example

services:
    localisation.service:
        class: Tinkernote\SiteBundle\Services\Localisation
        arguments: [@doctrine]

    recherche.service:
            class: Tinkernote\SiteBundle\Services\Recherche
            arguments: [@doctrine]

    tinkernote.form.type.tel:
        class: Tinkernote\SiteBundle\Form\Type\TelType
        tags:
            - { name: form.type, alias: tel }
