parameters:
#    site.example.class: Tinkernote\SiteBundle\Example

services:
    localisation.service:
        class: Tinkernote\SiteBundle\Services\Localisation
        arguments: [@doctrine]

    activity.service:
            class: Tinkernote\SiteBundle\Services\Activity
            arguments: [@doctrine, @security.context]

    tinkernote.form.type.tel:
        class: Tinkernote\SiteBundle\Form\Type\TelType
        tags:
            - { name: form.type, alias: tel }

    stats.service:
        class: Tinkernote\SiteBundle\Services\Stats
        arguments: [@doctrine, @security.context]

    abonnement.service:
        class: Tinkernote\SiteBundle\Services\Abonnement
        arguments: [@doctrine.orm.entity_manager, @security.context]
