<?php

namespace Tinkernote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRepository extends EntityRepository
{
    public function followed($user)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a','b')
            ->leftJoin('a.follower', 'b')
            ->where('b.id = :follower')
            ->setParameter('follower', $user);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
