<?php

namespace Tinkernote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbonnementRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbonnementRegionRepository extends EntityRepository
{
    public function getFollower($region, $user){
        $qb = $this->createQueryBuilder('a')
                    ->setMaxResults(5)
                    ->where('a.user != :user')
                    ->setParameter('user', $user)
                    ->getQuery();

        $result = $qb->getResult();

        return $result;
    }
}
