<?php

namespace Tinkernote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends EntityRepository
{
    /**
     * @param $recherche
     * @return array
     * '%' permet de rechercher un mot dans un texte
     * sinon il faut mettre le texte complet du genre "Le titre de l'annonce"
     * au lieu de simplement "annonce" ou "titre" etc.
     */
    public function recherche($recherche = null, $region = null){

        $qb = $this->createQueryBuilder('a')
                    ->select('a')
                    ->where('a.title like :recherche')
                    ->Orwhere('a.region = :region')
                    ->setParameter('region', $region)
                    ->setParameter('recherche', '%'.$recherche.'%');

        return $qb->getQuery()->getResult();
    }

    public function findByWords($words)
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.title like :words')
            ->Orwhere('a.content like :words')
            ->setParameter('words', '%'.$words.'%');

        return $qb->getQuery()->getResult();
    }
}
