<?php

namespace Tinkernote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function Category($parentcategory)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.parentcategory = :parentcategory')
            ->setParameter('parentcategory', $parentcategory);

        return $qb->getQuery()
            ->getArrayResult();
    }
}
