<?php

namespace Tinkernote\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
    public function getAdress()
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a, b, c')
            ->leftJoin('a.departement', 'b')
            ->leftJoin('b.region', 'c')
            ->addSelect('a.ville','b.departement','c.region','b.numero');
        return $qb->getQuery()->getResult();
    }

    public function Ville($departement)
    {
        $qb = $this->createQueryBuilder('v')
            ->where('v.departement = :departement')
            ->setParameter('departement', $departement);

        return $qb->getQuery()
            ->getArrayResult();
    }

}